trigger:
  - master

pool:
  name: 'Hosted Windows 2019 with VS2019'

variables:
  PACKAGE_VERSION: 1.0.1
  BUILD_NUMBER: $[counter(format('{0}_{1}', variables['PACKAGE_VERSION'], variables['Build.SourceBranch']), 1)]
  ASSEMBLY_VERSION: $(PACKAGE_VERSION).$(BUILD_NUMBER)

steps:
  - task: UseDotNet@2
    inputs:
      version: 3.x
      performMultiLevelLookup: true
  - pwsh: dotnet pack nano-api-scan -c Release -o output /p:Version=$(ASSEMBLY_VERSION) /p:PackageVersion=$(PACKAGE_VERSION)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: output
      artifactName: nuget
